version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"  # Expose Jupyter Notebook port
    volumes:
      - .:/home/jovyan/work  # Mount current directory into the container
    depends_on:
      - mongodb  # Ensure MongoDB starts before Jupyter
    command: >
      bash -c "pip install -r /home/jovyan/work/requirements.txt &&
           start-notebook.sh"

volumes:
  mongodb_data:





  # docker ps, list out the running docker contaner
  # docker compose -f <file name>.yml up -d, to run compose file
  # docker logs <container name>, to check the activity 
  # docker compose -f <file name>.yml down, stop and remove container



  # docker exec -it mongodb bash, to access the container
  # mongosh, to connect to shell of that mongodb container
  # show dbs;, to show all database list in that instances
  #     use yellow_pages; | use container;, to use specific database to interact with( in our case, we have container as our database)
  # db.yellow_pages.countDocuments(); | db.container_collection.countDocuments();, it will say how many collection are there in that collection.
  # db.yellow_pages.find().limit(5).pretty() | db.container_collection.find().limit(5).pretty();, print first 5 collection
  # exit, to exit the container




